/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang \
-x \
objective-c \
-target \
arm64-apple-ios11.0-simulator \
-fmessage-length\=0 \
-fdiagnostics-show-note-include-stack \
-fmacro-backtrace-limit\=0 \
-std\=gnu11 \
-fobjc-arc \
-fmodules \
-gmodules \
-fmodules-cache-path\=/Users/thiago/Library/Developer/Xcode/DerivedData/ModuleCache.noindex \
-fmodules-prune-interval\=86400 \
-fmodules-prune-after\=345600 \
-fbuild-session-file\=/Users/thiago/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation \
-fmodules-validate-once-per-build-session \
-Wnon-modular-include-in-framework-module \
-Werror\=non-modular-include-in-framework-module \
-Wno-trigraphs \
-fpascal-strings \
-O0 \
-fno-common \
-Wno-missing-field-initializers \
-Wno-missing-prototypes \
-Werror\=return-type \
-Wdocumentation \
-Wunreachable-code \
-Wno-implicit-atomic-properties \
-Werror\=deprecated-objc-isa-usage \
-Wno-objc-interface-ivars \
-Werror\=objc-root-class \
-Wno-arc-repeated-use-of-weak \
-Wimplicit-retain-self \
-Wduplicate-method-match \
-Wno-missing-braces \
-Wparentheses \
-Wswitch \
-Wunused-function \
-Wno-unused-label \
-Wno-unused-parameter \
-Wunused-variable \
-Wunused-value \
-Wempty-body \
-Wuninitialized \
-Wconditional-uninitialized \
-Wno-unknown-pragmas \
-Wno-shadow \
-Wno-four-char-constants \
-Wno-conversion \
-Wconstant-conversion \
-Wint-conversion \
-Wbool-conversion \
-Wenum-conversion \
-Wno-float-conversion \
-Wnon-literal-null-conversion \
-Wobjc-literal-conversion \
-Wshorten-64-to-32 \
-Wpointer-sign \
-Wno-newline-eof \
-Wno-selector \
-Wno-strict-selector-match \
-Wundeclared-selector \
-Wdeprecated-implementations \
-DDEBUG\=1 \
-DOBJC_OLD_DISPATCH_PROTOTYPES\=0 \
-isysroot \
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.4.sdk \
-fstrict-aliasing \
-Wprotocol \
-Wdeprecated-declarations \
-g \
-Wno-sign-conversion \
-Winfinite-recursion \
-Wcomma \
-Wblock-capture-autoreleasing \
-Wstrict-prototypes \
-Wno-semicolon-before-method-body \
-Wno-unguarded-availability \
-fobjc-abi-version\=2 \
-fobjc-legacy-dispatch \
-index-store-path \
/Users/thiago/Library/Developer/Xcode/DerivedData/iOSApp-frrxxdgefswljmaayjgcihttruuq/Index/DataStore \
-I/Users/thiago/Library/Developer/Xcode/DerivedData/iOSApp-frrxxdgefswljmaayjgcihttruuq/Build/Products/Debug-iphonesimulator/include \
-I/Users/thiago/Library/Developer/Xcode/DerivedData/iOSApp-frrxxdgefswljmaayjgcihttruuq/Build/Intermediates.noindex/iOSApp.build/Debug-iphonesimulator/iOSApp.build/DerivedSources-normal/arm64 \
-I/Users/thiago/Library/Developer/Xcode/DerivedData/iOSApp-frrxxdgefswljmaayjgcihttruuq/Build/Intermediates.noindex/iOSApp.build/Debug-iphonesimulator/iOSApp.build/DerivedSources/arm64 \
-I/Users/thiago/Library/Developer/Xcode/DerivedData/iOSApp-frrxxdgefswljmaayjgcihttruuq/Build/Intermediates.noindex/iOSApp.build/Debug-iphonesimulator/iOSApp.build/DerivedSources \
-F/Users/thiago/Library/Developer/Xcode/DerivedData/iOSApp-frrxxdgefswljmaayjgcihttruuq/Build/Products/Debug-iphonesimulator \
-fno-color-diagnostics \
-MMD \
-MT \
dependencies \
-MF \
/Users/thiago/Library/Developer/Xcode/DerivedData/iOSApp-frrxxdgefswljmaayjgcihttruuq/Build/Intermediates.noindex/iOSApp.build/Debug-iphonesimulator/iOSApp.build/Objects-normal/arm64/main.d \
--serialize-diagnostics \
/Users/thiago/Library/Developer/Xcode/DerivedData/iOSApp-frrxxdgefswljmaayjgcihttruuq/Build/Intermediates.noindex/iOSApp.build/Debug-iphonesimulator/iOSApp.build/Objects-normal/arm64/main.dia \
-c \
/Users/thiago/Development/xcbuildkit/iOSApp/iOSApp/main.m \
-o \
/Users/thiago/Library/Developer/Xcode/DerivedData/iOSApp-frrxxdgefswljmaayjgcihttruuq/Build/Intermediates.noindex/iOSApp.build/Debug-iphonesimulator/iOSApp.build/Objects-normal/arm64/main.o \
-index-unit-output-path \
/iOSApp.build/Debug-iphonesimulator/iOSApp.build/Objects-normal/arm64/main.o
